kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: +QGk+eAsYwxR/CXUs+xDqc4fxLetyPboTpVlZmZBwoE=
      - identity: {}
